### ISSUE TITLE
how to run your code 

### ISSUE THREAD

**Issue by Heeyyy** [unilight/Generative-Compression#1]

**Comment by Heeyyy** [comment]
This is the first time I've run deep learning code on my computer. I don't know how to run your code.could you tell me what should i do? thank you very much.

**Comment by Heeyyy** [comment]
i have solved this problems。 yeah！！

**Comment by unilight** [comment]
Hey @Heeyyy sorry I just saw this now. Did you really figure how to run it? Did it work? How were your results? Because I totally forgot to complete the readme after I push this repo...I'm really sorry for that...
